import os

from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse, RedirectResponse
from fastapi.templating import Jinja2Templates

frontend_router = APIRouter()

base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

templates_dir = os.path.join(base_dir, "templates")

os.makedirs(templates_dir, exist_ok=True)

templates: Jinja2Templates | None = None

if os.path.exists(templates_dir):
    templates = Jinja2Templates(directory=templates_dir)


@frontend_router.get("/", response_class=HTMLResponse)
async def serve_dashboard(request: Request) -> HTMLResponse:
    """
    Serve the cryptocurrency price dashboard.

    This endpoint returns an HTML page with real-time price display,
    historical data viewing, and manual refresh controls.

    Fallback: If Jinja2 templates are not available (e.g., Jinja2 not installed
    or templates directory missing), returns a basic HTML page with error
    information and links to API endpoints.

    Args:
        request: FastAPI Request object (required by Jinja2)

    Returns:
        HTMLResponse: Rendered dashboard or fallback error page
    """
    if templates is None:
        html_content = """
        <!DOCTYPE html>
        <html>
        <head>
            <title>Crypto Price Dashboard</title>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    padding: 20px;
                    text-align: center;
                }
                .error {
                    color: red;
                    margin: 20px;
                    padding: 20px;
                    border: 1px solid red;
                    border-radius: 5px;
                }
            </style>
        </head>
        <body>
            <h1>Crypto Price Dashboard</h1>
            <div class="error">
                <p>Dashboard template not found. Please check that:</p>
                <ul>
                    <li>The templates directory exists</li>
                    <li>index.html is in the templates directory</li>
                    <li>Jinja2 is installed</li>
                </ul>
                <p>API is available at:</p>
                <ul>
                    <li><a href="/docs">API Documentation (Swagger)</a></li>
                    <li><a href="/api/prices/latest?ticker=btc_usd">Latest BTC Price</a></li>
                    <li><a href="/api/prices/latest?ticker=eth_usd">Latest ETH Price</a></li>
                </ul>
            </div>
        </body>
        </html>
        """
        return HTMLResponse(content=html_content)

    return templates.TemplateResponse("index.html", {"request": request})


@frontend_router.get("/health", response_class=HTMLResponse)
async def health_check() -> HTMLResponse:
    """
    Simple health check endpoint for the frontend.

    Returns a basic HTML page indicating the dashboard is running.
    Useful for monitoring and basic connectivity checks.

    Returns:
        HTMLResponse: Simple HTML page with health status
    """
    return HTMLResponse(content="<h1>Dashboard is running</h1><p>Server is healthy</p>")


@frontend_router.get("/api-docs-redirect")
async def redirect_to_docs() -> RedirectResponse:
    """
    Redirect to API documentation (Swagger UI).

    Provides a convenient redirect endpoint to access the interactive
    API documentation generated by FastAPI.

    Returns:
        RedirectResponse: HTTP 307 redirect to /docs endpoint

    Notes:
        - Uses HTTP 307 (Temporary Redirect) to preserve request method
        - Useful for creating easy-to-remember URLs for documentation
    """

    return RedirectResponse(url="/docs")
